services:
  - type: web
    name: excel-chatbot
    env: python
    plan: free
    buildCommand: |
      chmod +x ./render-build.sh
      ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false

